/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Bean.PerguntaBean;
import Dao.PerguntaDao;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Convidado
 */
public class TelaPesquisarPergunta extends javax.swing.JFrame {

    /**
     * Creates new form TelaManterPergunta
     */
    public static ImageIcon icopes = new ImageIcon("src\\icones\\Zoom-icon16_1.png");
    public static ImageIcon icoalt = new ImageIcon("src\\icones\\Document-Write-icon16.png");
    public static ImageIcon iconov = new ImageIcon("src\\icones\\Document-Blank-icon16.png");
    public static ImageIcon icoexc = new ImageIcon("src\\icones\\Delete-icon16.png");

    public TelaPesquisarPergunta() {
        initComponents();
        setResizable(false);
        iconeBotoes();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btPesquisar);
       // validaBotoes();
    }

    private List<PerguntaBean> listaPerguntas;

    private PerguntaBean retornaObjeto() {
        PerguntaBean pergunta = new PerguntaBean();
        pergunta.setDescricao(TxaPergunta.getText().trim());
        return pergunta;
    }

    private void iconeBotoes() {
        btPesquisar.setIcon(icopes);
        btAlterar.setIcon(icoalt);
        btNovo.setIcon(iconov);
        btExcluir.setIcon(icoexc);
    }
    
    private void validaBotoes(){
        if (tabelaPergunta.getSelectedRow() == -1) {
            btAlterar.setEnabled(false);
            btExcluir.setEnabled(false);
        }else if(tabelaPergunta.getSelectedRow() != -1){
            btAlterar.setEnabled(true);
            btExcluir.setEnabled(true);
        }
    }
        
    private void AtualizaTabPergunta() {
        try {
            listaPerguntas = PerguntaDao.RetornaPerguntas(retornaObjeto());
            DefaultTableModel modeloperg = (DefaultTableModel) tabelaPergunta.getModel();
            modeloperg.setNumRows(0);
            for (PerguntaBean per : listaPerguntas) {
                modeloperg.addRow(new Object[]{
                    per.getDescricao(),
                    per.getCategoria().getDescricao(),
                    per.getNivel().getDescricao(),
                });
            }
             
            if (listaPerguntas.size() == 0) {
                lbMensg.setText("Não há perguntas registradas");
            } else if (listaPerguntas.size() == 1) {
                lbMensg.setText("Há apenas uma pergunta registrada");
            } else {
                lbMensg.setText("Há " + listaPerguntas.size() + " perguntas registradas");
            }
            lbMensg.setForeground(Color.black);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPergunta = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxaPergunta = new javax.swing.JTextArea();
        lbPergunta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbOrdenacao = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        lbMensg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisar Perguntas");

        tabelaPergunta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pergunta(s)", "Categoria", "Nível"
            }
        ));
        jScrollPane2.setViewportView(tabelaPergunta);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btNovo);

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btAlterar);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btExcluir);

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        TxaPergunta.setColumns(20);
        TxaPergunta.setRows(5);
        jScrollPane1.setViewportView(TxaPergunta);

        lbPergunta.setText("Pergunta:");

        jLabel1.setText("Ordenar:");

        cbOrdenacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pergunta", "Categoria", "Nível" }));
        cbOrdenacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrdenacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbPergunta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbOrdenacao, 0, 124, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPergunta)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btPesquisar)
                            .addComponent(cbOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.add(lbMensg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        if (TxaPergunta.getText().length() > 1) {
            AtualizaTabPergunta();
           
        } else {
            lbMensg.setText("A pesquisa deve ter ao menos 2 caracteres");
            lbMensg.setForeground(Color.red);
            DefaultTableModel modelo = (DefaultTableModel) tabelaPergunta.getModel();
            modelo.setNumRows(0);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        new TelaNovaPergunta(this, true).setVisible(true);
    }//GEN-LAST:event_btNovoActionPerformed


    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (tabelaPergunta.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Nenhuma pergunta selecionada para a exclusão!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            TxaPergunta.requestFocus();
        } else {
            PerguntaBean pergunta = listaPerguntas.get(tabelaPergunta.getSelectedRow());
            try {
                int opc = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a pergunta?");
                if (opc == JOptionPane.YES_OPTION) {
                    PerguntaDao.excluir(pergunta);
                    AtualizaTabPergunta();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed


    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if (tabelaPergunta.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Nenhuma pergunta selecionada para a alteração!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            TxaPergunta.requestFocus();
        } else {
            PerguntaBean pergunta = listaPerguntas.get(tabelaPergunta.getSelectedRow());
            new TelaNovaPergunta(this, true, pergunta).setVisible(true);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void cbOrdenacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrdenacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrdenacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisarPergunta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxaPergunta;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbOrdenacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMensg;
    private javax.swing.JLabel lbPergunta;
    private javax.swing.JTable tabelaPergunta;
    // End of variables declaration//GEN-END:variables
}
