/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Aluno 26
 */
public class TelaEscolhaDica extends javax.swing.JPanel {

    /**
     * Creates new form TelaEscolhaDica
     */
    public TelaEscolhaDica() {
        initComponents();
        
        //util.UtilInterface.ICONE_DICASOM.setImage(util.UtilInterface.ICONE_DICASOM.getImage().getScaledInstance(WIDTH, WIDTH, WIDTH));
        lbDicaSom.setIcon(util.UtilInterface.ICONE_DICASOM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnImagem = new javax.swing.JButton();
        btnSom = new javax.swing.JButton();
        btnTexto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbDicaSom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        btnImagem.setText("Imagem");
        jPanel1.add(btnImagem);

        btnSom.setText("Som");
        btnSom.setMaximumSize(new java.awt.Dimension(71, 23));
        btnSom.setMinimumSize(new java.awt.Dimension(71, 23));
        btnSom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomActionPerformed(evt);
            }
        });
        jPanel1.add(btnSom);

        btnTexto.setText("Texto");
        jPanel1.add(btnTexto);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel2.add(lbDicaSom);
        jPanel2.add(jLabel1);
        jPanel2.add(jLabel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSomActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImagem;
    private javax.swing.JButton btnSom;
    private javax.swing.JButton btnTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbDicaSom;
    // End of variables declaration//GEN-END:variables
}
