/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author user
 */
public class TelaEscolhaDicas extends javax.swing.JDialog {

    /**
     * Creates new form TelaEscolhaDicas
     */
    public TelaEscolhaDicas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ConfiguraComponentes();
    }

    private void ConfiguraComponentes() {
        setTitle("Escolha um tipo de dica(SOM,IMAGEM,TEXTO)");
        util.UtilInterface.ICONE_DICASOM.setImage(util.UtilInterface.ICONE_DICASOM.getImage().getScaledInstance(313, 300, 100));
        util.UtilInterface.ICONE_DICAIMAGEM.setImage(util.UtilInterface.ICONE_DICAIMAGEM.getImage().getScaledInstance(322, 300, 100));
        util.UtilInterface.ICONE_DICATEXTO.setImage(util.UtilInterface.ICONE_DICATEXTO.getImage().getScaledInstance(322, 300, 100));
        lbSom.setIcon(util.UtilInterface.ICONE_DICASOM);
        lbTexto.setIcon(util.UtilInterface.ICONE_DICATEXTO);
        lbImagem.setIcon(util.UtilInterface.ICONE_DICAIMAGEM);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSom = new javax.swing.JLabel();
        lbTexto = new javax.swing.JLabel();
        lbImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbSom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeimagem.png"))); // NOI18N
        lbSom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSomMouseExited(evt);
            }
        });

        lbTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeimagem.png"))); // NOI18N
        lbTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTextoMouseExited(evt);
            }
        });

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconeimagem.png"))); // NOI18N
        lbImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbImagemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbImagemMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbSom, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(lbSom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbSomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSomMouseClicked
        // TODO add your handling code here:
        System.err.println("Clicou som!!");
    }//GEN-LAST:event_lbSomMouseClicked

    private void lbSomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSomMouseEntered
        // TODO add your handling code here:
        lbSom.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        lbSom.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbSomMouseEntered

    private void lbSomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSomMouseExited
        // TODO add your handling code here:
        lbSom.setBorder(null);
    }//GEN-LAST:event_lbSomMouseExited

    private void lbImagemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImagemMouseEntered
        // TODO add your handling code here:
        lbImagem.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        lbImagem.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbImagemMouseEntered

    private void lbImagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImagemMouseExited
        // TODO add your handling code here:
        lbImagem.setBorder(null);
    }//GEN-LAST:event_lbImagemMouseExited

    private void lbTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTextoMouseEntered
        // TODO add your handling code here:
        lbTexto.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        lbTexto.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbTextoMouseEntered

    private void lbTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTextoMouseExited
        // TODO add your handling code here:
        lbTexto.setBorder(null);
    }//GEN-LAST:event_lbTextoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaEscolhaDicas dialog = new TelaEscolhaDicas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbSom;
    private javax.swing.JLabel lbTexto;
    // End of variables declaration//GEN-END:variables
}
