/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.ImageIcon;
import util.UtilInterface;

/**
 *
 * @author Victorio
 */
public class TelaAdmin extends javax.swing.JDialog {

    /**
     * Creates new form TelaAdmin
     */
    public TelaAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Adminstrador");
        setSize(722, 449);
        ImageIcon img = new ImageIcon("src\\Telas\\imagens\\3d_bars-2560x1440.jpg");
        img.setImage(img.getImage().getScaledInstance(725, 453, 100));
        lbFundo.setIcon(img);
        configuraComponentes();
    }

    private void configuraComponentes() {
        //Menu Gerenciar
        submenuGerenciarJogadores.setIcon(UtilInterface.ICONE_IMAGEMUSERPADRAO);
        submenuGerenciarCategorias.setIcon(UtilInterface.ICONE_CATEGORIA);
        submenuGerenciarNiveis.setIcon(UtilInterface.ICONE_NIVEL);
        submenuGerenciarPalavras.setIcon(UtilInterface.ICONE_PALAVRA);
        submenuGerenciarPerguntas.setIcon(UtilInterface.ICONE_PERGUNTA);
        
        //Menu Jogar
        submenuJogarForca.setIcon(UtilInterface.ICONE_FORCA);
        submenuJogarPerguntas.setIcon(UtilInterface.ICONE_JOGOPERGUNTA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbFundo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menuSobre = new javax.swing.JMenu();
        submenuJogarForca = new javax.swing.JMenuItem();
        submenuJogarPerguntas = new javax.swing.JMenuItem();
        menuGerenciar = new javax.swing.JMenu();
        submenuGerenciarJogadores = new javax.swing.JMenuItem();
        submenuGerenciarCategorias = new javax.swing.JMenuItem();
        submenuGerenciarNiveis = new javax.swing.JMenuItem();
        submenuGerenciarPalavras = new javax.swing.JMenuItem();
        submenuGerenciarPerguntas = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lbFundo);
        lbFundo.setBounds(0, 0, 720, 450);

        menuSobre.setText("Jogar");

        submenuJogarForca.setText("Jogo da Forca");
        submenuJogarForca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuJogarForcaActionPerformed(evt);
            }
        });
        menuSobre.add(submenuJogarForca);

        submenuJogarPerguntas.setText("Jogo de Perguntas e Respostas");
        submenuJogarPerguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuJogarPerguntasActionPerformed(evt);
            }
        });
        menuSobre.add(submenuJogarPerguntas);

        Menu.add(menuSobre);

        menuGerenciar.setText("Gerenciar");

        submenuGerenciarJogadores.setText("Gerenciar Jogadores");
        submenuGerenciarJogadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenuGerenciarJogadoresMouseClicked(evt);
            }
        });
        submenuGerenciarJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuGerenciarJogadoresActionPerformed(evt);
            }
        });
        menuGerenciar.add(submenuGerenciarJogadores);

        submenuGerenciarCategorias.setText("Gerenciar Categorias");
        submenuGerenciarCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenuGerenciarCategoriasMouseClicked(evt);
            }
        });
        submenuGerenciarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuGerenciarCategoriasActionPerformed(evt);
            }
        });
        menuGerenciar.add(submenuGerenciarCategorias);

        submenuGerenciarNiveis.setText("Gerenciar Níveis");
        submenuGerenciarNiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuGerenciarNiveisActionPerformed(evt);
            }
        });
        menuGerenciar.add(submenuGerenciarNiveis);

        submenuGerenciarPalavras.setText("Gerenciar Palavras");
        submenuGerenciarPalavras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuGerenciarPalavrasActionPerformed(evt);
            }
        });
        menuGerenciar.add(submenuGerenciarPalavras);

        submenuGerenciarPerguntas.setText("Gerenciar Perguntas");
        submenuGerenciarPerguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuGerenciarPerguntasActionPerformed(evt);
            }
        });
        menuGerenciar.add(submenuGerenciarPerguntas);

        Menu.add(menuGerenciar);

        menuRelatorios.setText("Relatórios");
        Menu.add(menuRelatorios);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        Menu.add(menuSair);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenuGerenciarJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuGerenciarJogadoresActionPerformed
        // TODO add your handling code here:
        new TelaPesquisaJogadores(this, true).setVisible(true);
    }//GEN-LAST:event_submenuGerenciarJogadoresActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuSairMouseClicked

    private void submenuGerenciarJogadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenuGerenciarJogadoresMouseClicked
        // TODO add your handling code here:
        new TelaPesquisaJogadores(this, true).setVisible(true);
    }//GEN-LAST:event_submenuGerenciarJogadoresMouseClicked

    private void submenuGerenciarCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenuGerenciarCategoriasMouseClicked
        // TODO add your handling code here:
        new TelaPesquisarCategoria(null, true).setVisible(true);
    }//GEN-LAST:event_submenuGerenciarCategoriasMouseClicked

    private void submenuGerenciarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuGerenciarCategoriasActionPerformed
        // TODO add your handling code here:
        new TelaPesquisarCategoria(null, true).setVisible(true);
    }//GEN-LAST:event_submenuGerenciarCategoriasActionPerformed

    private void submenuGerenciarNiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuGerenciarNiveisActionPerformed
        // TODO add your handling code here:
        new TelaPesquisarNivel(null, true).setVisible(true);
    }//GEN-LAST:event_submenuGerenciarNiveisActionPerformed

    private void submenuGerenciarPalavrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuGerenciarPalavrasActionPerformed
        // TODO add your handling code here:
        new TelaPesquisaPalavra().setVisible(true);
    }//GEN-LAST:event_submenuGerenciarPalavrasActionPerformed

    private void submenuGerenciarPerguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuGerenciarPerguntasActionPerformed
        // TODO add your handling code here:
        new TelaPesquisarPergunta().setVisible(true);
    }//GEN-LAST:event_submenuGerenciarPerguntasActionPerformed

    private void submenuJogarForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuJogarForcaActionPerformed
        // TODO add your handling code here:
        new Telajogo().setVisible(true);
    }//GEN-LAST:event_submenuJogarForcaActionPerformed

    private void submenuJogarPerguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuJogarPerguntasActionPerformed
        // TODO add your handling code here:
        new TelaJogoPerguntaResposta().setVisible(true);
    }//GEN-LAST:event_submenuJogarPerguntasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAdmin dialog = new TelaAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JMenu menuGerenciar;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem submenuGerenciarCategorias;
    private javax.swing.JMenuItem submenuGerenciarJogadores;
    private javax.swing.JMenuItem submenuGerenciarNiveis;
    private javax.swing.JMenuItem submenuGerenciarPalavras;
    private javax.swing.JMenuItem submenuGerenciarPerguntas;
    private javax.swing.JMenuItem submenuJogarForca;
    private javax.swing.JMenuItem submenuJogarPerguntas;
    // End of variables declaration//GEN-END:variables
}
