/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.ImageIcon;

/**
 *
 * @author Victorio
 */
public class TelaAdmin extends javax.swing.JDialog {

    /**
     * Creates new form TelaAdmin
     */
    public TelaAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Adminstrador");
        setSize(722,449);
        ImageIcon img = new ImageIcon("src\\Telas\\imagens\\3d_bars-2560x1440.jpg");
        img.setImage(img.getImage().getScaledInstance(725, 453, 100));
       lbFundo.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/niveisicon.png"))); // NOI18N
        jButton3.setText("Gerenciar Níveis");
        getContentPane().add(jButton3);
        jButton3.setBounds(500, 170, 180, 79);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/palavrasicon.png"))); // NOI18N
        jButton2.setText("Gerenciar Palavras");
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 210, 190, 90);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/questionicon.png"))); // NOI18N
        jButton1.setText("Gerenciar Perguntas");
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 260, 180, 79);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 249, 255));
        jLabel1.setText("    Bem Vindo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 360, 60);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/categorieicon.png"))); // NOI18N
        jButton4.setText("Gerenciar Categorias");
        getContentPane().add(jButton4);
        jButton4.setBounds(40, 260, 190, 79);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/usericon_1.png"))); // NOI18N
        jButton5.setText("Gerenciar Usuários");
        getContentPane().add(jButton5);
        jButton5.setBounds(40, 170, 190, 79);
        getContentPane().add(lbFundo);
        lbFundo.setBounds(0, 0, 720, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAdmin dialog = new TelaAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbFundo;
    // End of variables declaration//GEN-END:variables
}
