/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Bean.NivelBean;
import Dao.NivelDao;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import util.LimitaCaracteres;
import util.Relatorio;
import util.UtilInterface;

/**
 *
 * @author Administrador
 */
public class TelaPesquisarNivel extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisaNivel
     */
//    public static ImageIcon icopes = new ImageIcon("src\\icones\\Zoom-icon16_1.png");
//    public static ImageIcon icoalt = new ImageIcon("src\\icones\\Document-Write-icon16.png");
//    public static ImageIcon iconov = new ImageIcon("src\\icones\\Document-Blank-icon16.png");
//    public static ImageIcon icoexc = new ImageIcon("src\\icones\\Delete-icon16.png");
//    public static ImageIcon icorel = new ImageIcon("src\\icones\\relatorio_icone.jpg");
    public TelaPesquisarNivel(java.awt.Frame parent, boolean modal) {
        initComponents();
        txNivel.setDocument(new LimitaCaracteres(45));
        setResizable(false);
//        iconeBotoes();
        configuraComponentes();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btPesquisar);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
    }

    private List<NivelBean> listaNivel;

    private NivelBean retornaObjeto() {
        NivelBean nivel = new NivelBean();
        nivel.setDescricao(txNivel.getText());
        return nivel;
    }

    private void configuraComponentes() {
        btAlterar.setIcon(UtilInterface.ICONE_ALTERAR);
        btExcluir.setIcon(UtilInterface.ICONE_REMOVER);
        btImprimir.setIcon(UtilInterface.ICONE_RELATORIO);
        btNovo.setIcon(UtilInterface.ICONE_NOVO);
        btPesquisar.setIcon(UtilInterface.ICONE_PESQUISAR);
        lbMensg.setFont(UtilInterface.FONTE_PADRAO);
        lbNivel.setFont(UtilInterface.FONTE_PADRAO);
        txNivel.setFont(UtilInterface.FONTE_PADRAO);
    }

    private void iconeBotoes() {
//        btPesquisar.setIcon(icopes);
//        btAlterar.setIcon(icoalt);
//        btNovo.setIcon(iconov);
//        btExcluir.setIcon(icoexc);
//        btImprimir.setIcon(icorel);
    }

    private void validaBotoes() {
        if (tabelaNivel.getSelectedRow() == -1) {
            btAlterar.setEnabled(false);
            btExcluir.setEnabled(false);
        } else if (tabelaNivel.getSelectedRow() != -1) {
            btAlterar.setEnabled(true);
            btExcluir.setEnabled(true);
        }

    }

    private void AtualizaTabNivel() {
        try {
            listaNivel = NivelDao.RetornaNiveis(retornaObjeto());
            DefaultTableModel modeloniv = (DefaultTableModel) tabelaNivel.getModel();
            modeloniv.setNumRows(0);
            for (NivelBean niv : listaNivel) {
                modeloniv.addRow(new Object[]{
                    niv.getDescricao()
                });
            }

            if (listaNivel.size() == 0) {
                lbMensg.setText("Não há registro de nível");
            } else if (listaNivel.size() == 1) {
                lbMensg.setText("Há apenas um registro de nível");
            } else {
                lbMensg.setText("Há " + listaNivel.size() + " registros de níveis");
            }
            lbMensg.setForeground(Color.black);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbNivel = new javax.swing.JLabel();
        txNivel = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaNivel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbMensg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Níveis");

        jPanel4.setBackground(new java.awt.Color(153, 153, 225));

        lbNivel.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbNivel.setText("Nível:*");

        txNivel.setToolTipText("Digite o nível desejado (ou as primeiras letras deste) neste campo para a pesquisa");

        btPesquisar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tabelaNivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Níveis"
            }
        ));
        tabelaNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaNivelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaNivel);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        btNovo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btNovo);

        btAlterar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btAlterar);

        btExcluir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btExcluir);

        btImprimir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(btImprimir);

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));
        jPanel3.add(lbMensg);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbNivel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txNivel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisar)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        if (txNivel.getText().length() > 1) {
            AtualizaTabNivel();
        } else {
            lbNivel.setForeground(Color.red);
            lbMensg.setText("A pesquisa deve ter ao menos 2 carcateres");
            lbMensg.setForeground(Color.red);
            DefaultTableModel modelo = (DefaultTableModel) tabelaNivel.getModel();
            modelo.setNumRows(0);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        lbNivel.setForeground(Color.black);
        lbMensg.setText("");
        new TelaNovoNivel().setVisible(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if (tabelaNivel.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Nenhum nível selecionado para a alteração!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            txNivel.requestFocus();
        } else {
            NivelBean nivel = listaNivel.get(tabelaNivel.getSelectedRow());
            new TelaNovoNivel(nivel).setVisible(true);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (tabelaNivel.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Nenhum nível selecionado para a exclusão!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            txNivel.requestFocus();
        } else {
            NivelBean nivel = listaNivel.get(tabelaNivel.getSelectedRow());
            try {
                int opc = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a categoria?");
                if (opc == JOptionPane.YES_OPTION) {
                    NivelDao.DeletarNivel(nivel);
                    AtualizaTabNivel();
                    validaBotoes();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:
        try {
            if (txNivel.getText().trim().equalsIgnoreCase("")) {
                Relatorio.gerarRelatorio("relatorios\\ListagemDeNiveis.jasper", NivelDao.retornaRsSemObjeto());
            }else{
                Relatorio.gerarRelatorio("relatorios\\ListagemDeNiveis.jasper", NivelDao.retornaRsComObjeto(retornaObjeto()));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (JRException ex) {
            ex.printStackTrace();
            Logger.getLogger(TelaPesquisarNivel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btImprimirActionPerformed

    private void tabelaNivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaNivelMouseClicked
        // TODO add your handling code here:
        validaBotoes();
    }//GEN-LAST:event_tabelaNivelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisarNivel(null, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMensg;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JTable tabelaNivel;
    private javax.swing.JTextField txNivel;
    // End of variables declaration//GEN-END:variables
}
