/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Bean.CategoriaBean;
import Dao.CategoriaDao;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import util.LimitaCaracteres;
import util.Relatorio;
import util.UtilInterface;

/**
 *
 * @author Administrador
 */
public class TelaPesquisarCategoria extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisarCategoria
     */
//    public static ImageIcon icopes = new ImageIcon("src\\icones\\Zoom-icon16_1.png");
//    public static ImageIcon icoalt = new ImageIcon("src\\icones\\Document-Write-icon16.png");
//    public static ImageIcon iconov = new ImageIcon("src\\icones\\Document-Blank-icon16.png");
//    public static ImageIcon icoexc = new ImageIcon("src\\icones\\Delete-icon16.png");
//    public static Relatorio rel = new Relatorio();
//    public static ImageIcon icorel = new ImageIcon("src\\icones\\relatorio_icone.jpg");
//    
    public TelaPesquisarCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txCategoria.setDocument(new LimitaCaracteres(45));
        setResizable(false);
//        iconeBotoes();
        configuraComponentes();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btPesquisar);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        UtilInterface.setFontes(p4.getComponents());
        UtilInterface.setFontes(p3.getComponents());
    }

    private List<CategoriaBean> listaCategoria;

    private CategoriaBean retornaObjeto() {
        CategoriaBean categoria = new CategoriaBean();
        categoria.setDescricao(txCategoria.getText());
        return categoria;
    }

    private void configuraComponentes() {
        btAlterar.setIcon(UtilInterface.ICONE_ALTERAR);
        btExcluir.setIcon(UtilInterface.ICONE_REMOVER);
        btImprimir.setIcon(UtilInterface.ICONE_RELATORIO);
        btNovo.setIcon(UtilInterface.ICONE_NOVO);
        btPesquisar.setIcon(UtilInterface.ICONE_PESQUISAR);
        lbMensg.setFont(UtilInterface.FONTE_PADRAO);
        lbCategoria.setFont(UtilInterface.FONTE_PADRAO);
        txCategoria.setFont(UtilInterface.FONTE_PADRAO);
    }

    private void iconeBotoes() {
//        btPesquisar.setIcon(icopes);
//        btAlterar.setIcon(icoalt);
//        btNovo.setIcon(iconov);
//        btExcluir.setIcon(icoexc);
//        btImprimir.setIcon(icorel);
    }

    private void validaBotoes() {
        if (tabelaCategoria.getSelectedRow() == -1) {
            btAlterar.setEnabled(false);
            btExcluir.setEnabled(false);
        } else if (tabelaCategoria.getSelectedRow() != -1) {
            btAlterar.setEnabled(true);
            btExcluir.setEnabled(true);
        }

    }

    private void AtualizaTabCategoria() {
        try {
            listaCategoria = CategoriaDao.retornaCategoria(retornaObjeto());
            DefaultTableModel modelocateg = (DefaultTableModel) tabelaCategoria.getModel();
            modelocateg.setNumRows(0);
            for (CategoriaBean cat : listaCategoria) {
                modelocateg.addRow(new Object[]{
                    cat.getDescricao()
                });
            }

            if (listaCategoria.size() == 0) {
                lbMensg.setText("Não há registro de categoria");
            } else if (listaCategoria.size() == 1) {
                lbMensg.setText("Há apenas um registro de categoria");
            } else {
                lbMensg.setText("Há " + listaCategoria.size() + " registros de categoria");
            }
            lbMensg.setForeground(Color.black);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p4 = new javax.swing.JPanel();
        txCategoria = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        lbCategoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCategoria = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbMensg = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Categorias");

        p4.setBackground(new java.awt.Color(153, 153, 225));

        txCategoria.setToolTipText("Digite a categoria desejada (ou as primeiras letras desta) neste campo para a pesquisa");

        btPesquisar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        lbCategoria.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbCategoria.setText("Categoria:*");

        tabelaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria(s)"
            }
        ));
        tabelaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCategoria);

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));
        jPanel3.add(lbMensg);

        p3.setBackground(new java.awt.Color(255, 255, 0));

        btNovo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        p3.add(btNovo);

        btAlterar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        p3.add(btAlterar);

        btExcluir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        p3.add(btExcluir);

        btImprimir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });
        p3.add(btImprimir);

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addComponent(txCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(p4Layout.createSequentialGroup()
                        .addComponent(lbCategoria)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(p3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        lbCategoria.setForeground(Color.black);
        lbMensg.setText("");
        new TelaNovaCategoria(null, true).setVisible(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if (tabelaCategoria.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Nenhuma categoria selecionada para a alteração!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            txCategoria.requestFocus();
        } else {
            CategoriaBean categoria = listaCategoria.get(tabelaCategoria.getSelectedRow());
            new TelaNovaCategoria(null, true, categoria).setVisible(true);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (tabelaCategoria.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Nenhuma categoria selecionada para a exclusão!", "ERRO!", JOptionPane.ERROR_MESSAGE);
            txCategoria.requestFocus();
        } else {
            CategoriaBean categoria = listaCategoria.get(tabelaCategoria.getSelectedRow());
            try {
                int opc = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a categoria?");
                if (opc == JOptionPane.YES_OPTION) {
                    CategoriaDao.excluir(categoria);
                    AtualizaTabCategoria();
                    validaBotoes();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        if (txCategoria.getText().length() > 1) {
            AtualizaTabCategoria();
        } else {
            lbCategoria.setForeground(Color.red);
            lbMensg.setText("A pesquisa deve ter ao menos 2 carcateres");
            lbMensg.setForeground(Color.red);
            DefaultTableModel modelo = (DefaultTableModel) tabelaCategoria.getModel();
            modelo.setNumRows(0);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        try {
            Relatorio.gerarRelatorio("Relatorios\\RelatorioCategoria.jasper", CategoriaDao.retornaRs(retornaObjeto()));
        } catch (SQLException e) {
        } catch (JRException ex) {
            Logger.getLogger(TelaPesquisarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void tabelaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCategoriaMouseClicked
        // TODO add your handling code here:
        validaBotoes();
    }//GEN-LAST:event_tabelaCategoriaMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPesquisarCategoria dialog = new TelaPesquisarCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbMensg;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JTable tabelaCategoria;
    private javax.swing.JTextField txCategoria;
    // End of variables declaration//GEN-END:variables
}
